version: '2.2'

services:
    node:
        build: 
            context: ./js
            dockerfile: Dockerfile
        scale: 3
    nginx:
        image: nginx:1.17.3
        ports:
            - "5555:80"
        volumes:
            - ./replicated_nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node
    graphite:
        image: graphiteapp/graphite-statsd:1.1.5-12
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:6.3.3
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: google/cadvisor:v0.33.0
        privileged: true
        links:
            - graphite
        privileged: true
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
volumes:
    grafana_config:
        driver: local
